### ISSUE TITLE
request [Error: header too long]

### ISSUE THREAD

**Issue by tigerui** [tvrcgo/weixin-pay#12]
request({
        url: "https://api.mch.weixin.qq.com/pay/unifiedorder",
        method: 'POST',
        body: util.buildXML(opts),
        agentOptions: {
            pfx: this.options.pfx,
            passphrase: this.options.mch_id
        }
    }, function(err, response, body){
        console.log(err);
        util.parseXML(body, fn);
    });
求解

**Comment by tvrcgo** [comment]
@tigerui 检查传的 body
