### ISSUE TITLE
使用模式一支付的问题

### ISSUE THREAD

**Issue by thinkive** [tvrcgo/weixin-pay#13]
我这边遇到一个奇怪的问题
根据
var url = wxpay.createMerchantPrepayUrl({ product_id: '123456' }); 返回的二维码，用户也扫描了，同时
商户后台也收到微信的回调之后，并且也调用 createUnifiedOrder() 生成预支付交易单，返回如下内容
 { return_code: 'SUCCESS',
server-1   return_msg: 'OK',
server-1   appid: 'wxf5b3c80720abf32f1',
server-1   mch_id: '1367153302',
server-1   nonce_str: 'EVAtWsAxfdRCr7ld',
server-1   sign: '714448185388A8D61C9B80926F56C662
server-1   result_code: 'SUCCESS',
server-1   prepay_id: 'wx201607231446087ccd9d044c02411844123',
server-1   trade_type: 'NATIVE',
server-1   code_url: 'weixin://wxpay/bizpayurl?pr=XL8favn' }

请问到这一步后，我是需要把这个json转换为xml后，返回给微信吗？如何返回呢？

**Comment by hong26** [comment]
应该是需要返回xml,在你自己设置的那个原生回调url里面返回给微信支付系统.其实我最近正在看微信支付这方面的资料还没有账号可以测试,不知道我说的对不对.

**Comment by tvrcgo** [comment]
@thinkive 再好好了解下微信的支付注程图

现在已经没有模式一和二的区别了，统一接口。2.0开发中
