### ISSUE TITLE
无法获取微信返回状态

### ISSUE THREAD

**Issue by lihongwei-2016** [tvrcgo/weixin-pay#15]
支付定单返如如下结果：
{
  "appId": "wx4909c6e97b8f1f9c",
  "timeStamp": "1472203485",
  "nonceStr": "8OIWcyYFglN5qYIj",
  "package": "**prepay_id=undefined**",
  "signType": "MD5",
  "paySign": "7A11C65CBDFF98554AADC4059AAC70B6"
}.
微信接口有很多内容，但该包并没有返回，比如失败状态。
如果这些信息返回，就可以生产环境用了

**Comment by fengguo118** [comment]
我这个接口返回的是空

**Comment by tvrcgo** [comment]
@lihongwei-2016 @fengguo118 working on v2.0
