### ISSUE TITLE
支付结果异步通知，自己访问也会执行业务逻辑

### ISSUE THREAD

**Issue by liaolunhui** [tvrcgo/weixin-pay#2]
我自己访问/wxpay/notify也会执行业务逻辑，此时msg=null，微信通知过来时，msg有订单信息。
那么问题来了，怎么判断通知是微信过来的，还是别人冒充微信发过来的？

// 支付结果异步通知
router.use('/wxpay/notify', wxpay.useWXCallback(function(msg, req, res, next){
    // 处理商户业务逻辑
  //这里的代码自己访问也会执行
    // res.success() 向微信返回处理成功信息，res.fail()返回失败信息。
    res.success();
}));

**Comment by jipan25** [comment]
验签啊，在msg中有个sign字段，先调用wxpay.sign方法验签.

**Comment by xxd3vin** [comment]
验证签名的伪代码。也可以参照https://github.com/supersheep/wechat-pay/blob/master/lib/payment.js#L354

```javascript
// 支付结果异步通知
router.use('/wxpay/notify', wxpay.useWXCallback(function(msg, req, res, next){
  // 处理商户业务逻辑

  // > 这里的代码自己访问也会执行
  // 需要对微信发送的请求参数进行签名验证，具体过程参照https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_3
  // 一个小细节，需要删除`sign`参数，然后再签名。
  var pkg = _.clone(msg);
  delete pkg.sign;
  if (data.sign !== wxpay.sign(pkg)) {
    // 签名失败，请求不是来自于微信服务器。
  } else {
    // 签名成功，处理订单信息。
  }

  // res.success() 向微信返回处理成功信息，res.fail()返回失败信息。
  res.success();
}));
```
