### ISSUE TITLE
[TypeError: Cannot read property 'toString' of undefined]

### ISSUE THREAD

**Issue by channg** [tvrcgo/weixin-pay#24]
调用统一下单时 err返回值为这个

**Comment by tvrcgo** [comment]
@channg 描述太少，没办法帮到你

**Comment by garryzhong** [comment]
我也遇到了，调用退款接口的时候，err 不为空，但是 err console.log 打出来后，显示Cannot read property 'toString' of undefined

**Comment by garryzhong** [comment]
是我证书没设置，所以出错了。
