### ISSUE TITLE
has no method 'useWXCallback'

### ISSUE THREAD

**Issue by i5ting** [tvrcgo/weixin-pay#3]
```
router.get('/notify', wxpay.useWXCallback(function(msg, req, res, next){
                            ^
TypeError: Object function WXPay() {
	
	if (!(this instanceof WXPay)) {
		return new WXPay(arguments[0]);
	};

	this.options = arguments[0];
	this.wxpayID = { appid:this.options.appid, mch_id:this.options.mch_id };
} has no method 'useWXCallback'
```

**Comment by tvrcgo** [comment]
没实例化？

**Comment by i5ting** [comment]
中间件

商户服务端处理微信的回调（express为例）

var router = express.Router();
var wxpay = require('weixin-pay');

// 原生支付回调
router.use('/wxpay/native/callback', wxpay.useWXCallback(function(msg, req, res, next){
    // msg: 微信回调发送的数据
}));

// 支付结果异步通知
router.use('/wxpay/notify', wxpay.useWXCallback(function(msg, req, res, next){
    // 处理商户业务逻辑

    // res.success() 向微信返回处理成功信息，res.fail()返回失败信息。
    res.success();
}));

**Comment by i5ting** [comment]
这个是readme里的文档，你确定实例化？

**Comment by jipan25** [comment]
要实例化的
