### ISSUE TITLE
沙箱支持

### ISSUE THREAD

**Issue by zealseeker** [tvrcgo/weixin-pay#39]
目前调用微信的接口都是直接写死的地址，能否支持一下沙箱环境？
微信的支付接口升级必须要用沙箱环境测试才可通过
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=21515658940X5pIn

比如查询地址要改成：
（https://api.mch.weixin.qq.com/sandboxnew/pay/orderquery）

所以我建议用一个变量统一，比如
```
let host = 'https://api.mch.weixin.qq.com'
let sandboxName = '/sandboxnew'
...
url = host + sandboxName + '/orderquery'
```

**Comment by tvrcgo** [comment]
@zealseeker  这个建议好，我考虑进 v2.0

**Comment by qqaimh** [comment]
> @zealseeker 这个建议好，我考虑进 v2.0
请问，现在支持沙箱了吗？
