### ISSUE TITLE
调用js支付出错问题

### ISSUE THREAD

**Issue by Roonie1** [tvrcgo/weixin-pay#5]
调用js支付时返回这样的参数：  
nonceStr: undefined,
package: 'prepay_id=undefined',

求助！！！！！！

**Comment by tvrcgo** [comment]
仔细看下微信官方文档

**Comment by jinweida** [comment]
{ return_code: 'FAIL', return_msg: '签名错误' }

**Comment by jinweida** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
zc-0 <root>
zc-0   <body>ceshile</body>
zc-0   <out_trade_no>4160114100142232</out_trade_no>
zc-0   <total_fee>6</total_fee>
zc-0   <spbill_create_ip>121.43.114.111</spbill_create_ip>
zc-0   <notify_url>http://zc.joygo-dev.com/api-v1-0/weixin-notify</notify_url>
zc-0   <trade_type>APP</trade_type>
zc-0   <nonce_str>p0ROPSBW4L5iN9wH1GkjGCzQFRcY1y3r</nonce_str>
zc-0   <appid>wx201c8d5f6092d7c1</appid>
zc-0   <mch_id>1305097501</mch_id>
zc-0   <sign>FC94F88200CDC13760CEB3114377C692</sign>
zc-0 </root>

**Comment by i5ting** [comment]
我的也是这个错误。。。

**Comment by clm1100** [comment]
**一楼同学的问题解决了吗**

**Comment by clm1100** [comment]
桑老师也碰到这个问题了，怎么解决的，调试这一关都过不去

**Comment by beaulian** [comment]
我也遇到这个问题，现在没人维护了吗？

**Comment by zealseeker** [comment]
使用相同参数（自己加上trade_type='JSAPI'）这些参数创建一个统一订单，会返回错误内容
比如 { return_code: 'FAIL', return_msg: '您没有JSAPI支付权限' }  也可能是因为没有openid吧，反正我到这步就做不下去了，没开通。

**Comment by shenaishiren** [comment]
果然是我openid出错了

**Comment by beaulian** [comment]
原来是我的openid出错了

**Comment by panyunyi** [comment]
我也出现了同样的问题
